# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tableviewone.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableViewDialog(object):
    def setupUi(self, TableViewDialog):
        TableViewDialog.setObjectName("TableViewDialog")
        TableViewDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(TableViewDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(TableViewDialog)
        self.tableView.setEnabled(True)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)

        self.retranslateUi(TableViewDialog)
        QtCore.QMetaObject.connectSlotsByName(TableViewDialog)

    def retranslateUi(self, TableViewDialog):
        _translate = QtCore.QCoreApplication.translate
        TableViewDialog.setWindowTitle(_translate("TableViewDialog", "Dialog"))
